murmur_web/auth/urls.py
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    path('user/',     views.user, name='user'),
    path('vhost/',    views.vhost, name='vhost'),
    path('resource/', views.resource, name='resource'),
    path('topic/',    views.topic, name='topic')
]

murmur_web/core/urls.py
from django.urls import path, re_path, include
import django.contrib.auth.views as auth_views
from . import views

workspace_patterns = ([
    path('new/', views.workspace.create, name='create'),
    path('<str:ws_name>/', views.workspace.home, name='home'),
    path('<str:ws_name>/new', views.workspace.new_channel, name='new_channel'),
    path('<str:ws_name>/settings', views.workspace.settings, name='settings'),
], 'ws')

user_patterns = ([
    path('dashboard/', views.user.dashboard, name='dash'),
    path('settings/', views.user.settings, name='settings'),
    path('sudo/', views.user.sudo, name='sudo'),
], 'user')

urlpatterns = [
    path('', views.public.home, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='core/registration/login.html'), name='login'),
    path('register/', views.public.register, name='register'),
    path('', include('django.contrib.auth.urls')),
    path('u/', include(user_patterns, namespace='user')),
    path('w/', include(workspace_patterns, namespace='ws')),
]

murmur_web/murmur_web/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('auth/', include('auth.urls')),
]

murmur_web/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import core.rabbitmq

# Create your models here.
class Person(AbstractUser):
    email_verified = models.BooleanField(default=False)

    class Meta:
        unique_together = ('email',)


class RegistrationToken(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    token = models.CharField(max_length=32)
    is_verified = models.BooleanField(default=False)


class Channel(models.Model):
    name = models.CharField(max_length=120)
    members = models.ManyToManyField(Person, through='ChannelMembership', through_fields=('channel', 'person'))
    workspace = models.ForeignKey('Workspace', on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def get_messages(self, limit=20):
        messages = self.message_set.all().order_by('timestamp')[:limit]
        return [x.to_json() for x in messages]

    def __str__(self):
        return ("%s" % self.name)

    def create(ch_name, ws, user, initial_members=[]):
        ch = __class__(name=ch_name, workspace=ws)
        ch.save()
        for member in initial_members:
            ChannelMembership.objects.create(channel=ch, person=member, invited_by=user)
        ch.save()
        return ch


class ChannelMembership(models.Model):
    channel = models.ForeignKey(Channel, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    invited_by = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='invited_channel_members')
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('person', 'channel', 'invited_by')


class Workspace(models.Model):
    name = models.CharField(max_length=120, unique=True)
    members = models.ManyToManyField(Person, through='WorkspaceMembership', through_fields=('workspace', 'person'))
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('name',)

    def __str__(self):
        return ("%s" % self.name)

    def admin(self):
        return self.members.filter(workspacemembership__is_admin=True)
    
    def create_and_declare(name, admin, initial_members=[]):
        ws = __class__(name=name)
        ws.save()
        WorkspaceMembership.objects.create(workspace=ws,
                                           person=admin,
                                           invited_by=admin,
                                           is_admin=True)
        with core.rabbitmq.open() as ri:
            ri.declare_workspace(name, exchange_type='topic', durable=True)
        return ws


    def delete_and_purge(self):
        self.delete()
        with core.rabbitmq.open() as ri:
            ri.delete_workspace(self.name)

class WorkspaceMembership(models.Model):
    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    nick = models.CharField(max_length=120, blank=False)
    invited_by = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='invited_ws_members')
    is_admin = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('person', 'nick', 'workspace', 'invited_by', 'is_admin')

    def get_messages(self, reciever, limit=20):
        if reciever == self.person:
            sent_by_me = list(Message.objects.filter(workspace=self.workspace, reciever=reciever, sender=self.person))
            return [x.to_json() for x in sent_by_me]
        else:
            sent_by_me = Message.objects.filter(workspace=self.workspace, reciever=reciever, sender=self.person)
            recvd_by_me = Message.objects.filter(workspace=self.workspace, reciever=self.person, sender=reciever)
            return [x.to_json() for x in sent_by_me.union(recvd_by_me).order_by('timestamp')]

class Message(models.Model):
    message_id = models.CharField(max_length=25, primary_key=True)
    body = models.TextField()
    mtype = models.CharField(max_length=12)
    timestamp = models.DateTimeField(auto_now_add=True)
    sender = models.ForeignKey(Person, null=True, on_delete=models.SET_NULL, related_name='as_sender')
    reciever = models.ForeignKey(Person, null=True, on_delete=models.SET_NULL, related_name='as_reciever')
    channel = models.ForeignKey(Channel, on_delete=models.CASCADE, null=True)
    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE)
    parent = models.ForeignKey('Message', on_delete=models.CASCADE, null=True)

    class Meta:
        unique_together = ('message_id', 'sender', 'parent', 'workspace')

    def to_json(self):
        sender_nick_name = WorkspaceMembership.objects.get(workspace=self.workspace, person=self.sender).nick
        # reciever = None
        # if self.reciever:
        #     reciever_nick_name = WorkspaceMembership.objects.get(workspace=self.workspace, person=self.reciever).nick
        #     reciever = {'id': self.reciever.id,
        #                 'name': reciever_nick_name}
        return {'id': self.message_id,
                'body': self.body,
                'type': self.mtype,
                'timestamp': self.timestamp.isoformat(),
                'sender': {'id': self.sender.id,
                           'name': sender_nick_name},
                'parent': self.parent.id if self.parent else None,}
                # 'reciever': reciever}

murmur_web/core/views/public.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from . import user as user_views
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

import logging

logger = logging.getLogger(__name__)

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        User = get_user_model()
        model = User
        fields = ('username', 'email', 'password1', 'password2')


# Create your views here.
def home(request):
    if request.user.is_authenticated:
        return user_views.dashboard(request)
    else:
        return redirect('login')


def workspace(request):
    pass


def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('user:dash')
    else:
        form = SignUpForm()
    return render(request, 'core/registration/register.html', {'form': form})

murmur_web/core/views/user.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

import logging
logger = logging.getLogger(__name__)

# Create your views here.
@login_required
def dashboard(request):
    ws_list = [x.name for x in request.user.workspace_set.all()]
    return render(request, 'core/user/dashboard.html', {'ws_list': ws_list})


@login_required
def settings(request):
    return HttpResponse("wow, %s/settings" % request.user.username)

@login_required
def sudo(request):
    ws_name = 'utopia'
    channels = [x.name for x in request.user.channel_set.filter(workspace__name=ws_name).order_by('created_on')]
    members = [{'id': x.person.id,
                'name': x.nick}
               for x in WorkspaceMembership.objects
                   .filter(workspace__name=ws_name)
                   .order_by('created_on')]

    utils = {
        'channels': [{'name': c, 'id': '{}.{}'.format(ws_name, c)} for c in channels] + [None] + [{'name': m['name'], 'id': '{}.$user-{}'.format(ws_name, m['id'])} for m in members]}
    return render(request, 'core/user/sudo.html', {
        'channels': channels,
        'members': members,
        'workspace': ws_name,
        'utils': utils})

murmur_web/core/views/workspace.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from core.models import Workspace, Channel, WorkspaceMembership, ChannelMembership
from django.contrib.auth.decorators import login_required
# from core.permisions import permission_required
from django import forms
from django.apps import apps
import logging

logger = logging.getLogger(__name__)


class ws_form(forms.Form):
    ws_name = forms.CharField(label='New workspace name')
    ch_name = forms.CharField(label='Channel name', help_text="One is compulsory")

    class Meta:
        model = Workspace
        model = Channel


class ch_form(forms.Form):
    ch_name = forms.CharField(label='New channel name')

    class Meta:
        model = Channel


# Create your views here
'''
Any user can create a workspace and become it's admin.
In the form shown here:
* Get workspace name etc.
* Get Atleast 1 channel name.
* Get list of emails IDs (for invitations)
'''


@login_required
def create(request):
    if request.method == 'POST':
        form = ws_form(request.POST)
        if form.is_valid():
            ws_name = form.cleaned_data.get('ws_name')
            ch_name = form.cleaned_data.get('ch_name')
            admin = request.user
            ws = Workspace.create_and_declare(name=ws_name, admin=admin)
            Channel.create(ch_name=ch_name, ws=ws, user=admin, initial_members=[admin])
            return redirect('/')
    else:
        form = ws_form()
    return render(request, 'core/workspace/ws_create.html', {'form': form})


'''
Admins see all channels, others don't
'''


@login_required
def home(request, ws_name):
    if request.user.workspace_set.filter(name=ws_name).count() == 1:
        channels = request.user.channel_set.filter(workspace__name=ws_name).order_by('created_on')
        members = WorkspaceMembership.objects.filter(workspace__name=ws_name).order_by('created_on')
        messages = {channel.name: channel.get_messages(30) for channel in channels}
        private_stuff = {"$user-{}".format(member.person.id): member.get_messages(request.user, 30) for member in members}
        messages.update(private_stuff)
        utils = {
            'channels': [{'name': c.name, 'id': '{}.{}'.format(ws_name, c.name)} for c in channels] + [None] + [{'name': m.nick, 'id': '{}.$user-{}'.format(ws_name, m.person.id)} for m in members]}

        return render(request, 'core/workspace/home.html', {
            'channels': [x.name for x in channels],
            'members': [{'id': x.person.id,
                         'name': x.nick} for x in members],
            'workspace': ws_name,
            'utils': utils,
            'messages': messages,
            'is_admin': request.user.workspacemembership_set.filter(workspace__name=ws_name, is_admin=True).count() == 1})
    else:
        redirect('login')

'''
An admin should be able to
* Send invitation emails.
* Add/remove members of channels from the existing ws members.
* Remove members from ws (persons retain ws membership even when removed from all channels).
  - Removal from ws, leads to removal from all channels.
* Grant/revoke `workspace_admin` privilege to other members.
* Delete the workspace.
'''


@login_required
# @permission_required('core.workspace_admin')
def settings(request, ws_name):
    if request.user.workspace_set.filter(name=ws_name).count() == 1:
        # isadmin = request.user.workspacemembership_set.filter(workspace__name=ws_name, is_admin=True).count() == 1

        payload = {}
        channels = request.user.channel_set.filter(workspace__name=ws_name)
        for ch in channels:
            name = list()
            for mem in ChannelMembership.objects.filter(channel=ch).order_by('created_on'):
                name.append(mem.person.username)
            payload[ch.name] = name

        return render(request, 'core/workspace/ws_setting.html', {
        'data': payload, 'workspace': ws_name
        })

    # return render(request, 'core/workspace/ws_setting.html', {'ws_name': ws_name})

'''
In the form shown here:
* Get name, etc.
* List of workspace members to add in here.

Channel names cannot have `$` as the first character!
'''

@login_required
# @permission_required('core.workspace_admin')
def new_channel(request, ws_name):
    if request.method == 'POST':
        form = ch_form(request.POST)
        if form.is_valid():
            ch_name = form.cleaned_data.get('ch_name')
            admin = request.user
            ws = Workspace.objects.get(name=ws_name)
            Channel.create(ch_name=ch_name, ws=ws, user=admin, initial_members=[admin])
            return redirect('/')
    else:
        form = ch_form()
    return render(request, 'core/workspace/ws_newch.html', {'form': form, 'ws_name': ws_name})

murmur_web/core/templates/core/workspace/base.html
{% extends "core/base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/workspace.css' %}">
{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light usernavbar">
  {% block ws_navbar %}
  {% endblock %}
</nav>

<div class="container-fluid" style="height: 80vh; width:100%">
  <div class="row" style="height: 80vh; width:100%">
    <div id="sidebar" class="col-2">
      {% block sidebar %}
      {% endblock %}
    </div>
    <div id="main" class="col-xl">
      {% block main %}
      {% endblock %}
    </div>
  </div>
</div>
{% endblock %}

murmur_web/core/templates/core/workspace/home.html
{% extends "core/workspace/base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/workspace.css' %}">
{% endblock %}

{% block ws_navbar %}
{% include "core/workspace/navbar.html" %}
{% endblock %}

{% block sidebar %}
<div class="container">
  <h3>Channels</h3>
  <div id="channels">
    <div id="channel-list">
      <ul>
        {% for channel in utils.channels %}
        {% if forloop.first %}
        <li id={{ channel.id }} kind="channel" class="active">
          {{ channel.name }}
        </li>
        {% elif channel == None %}
      </ul>
      <h3>Members</h3>
      <div id="member-list">
        <ul>
          {% else %}
          <li id={{ channel.id }} kind="user">
            {{ channel.name }}
          </li>
          {% endif %}
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block main %}
<div id="channel-view">
  <div id="messages">
    <div id="message-1">
      <div class="sender" name="metallica" user_id="14">
        metallica
      </div>
      <div class="body">
        slayer is meh
      </div>
    </div>

    <div id="message-2">
      <div class="sender" name="metallica" user_id="14">
        metallica
      </div>
      <div class="body">
        sound of silence
      </div>
    </div>

    <div id="message-3">
      <div class="sender" name="metallica" user_id="14">
        metallica
      </div>
      <div class="body">
        peace.
      </div>
    </div>
  </div>
  <div id="inpform">
    <form><input autocomplete="off" placeholder="Type here..."></input></form>
  </div>
</div>

<div id="second" style="visibility: hidden;">
  LOGS
  <div></div>
</div>
{% endblock %}

{% block scripts %}
{{ workspace|json_script:'workspace-data' }};
{{ channels|json_script:'channels-data' }};
{{ members|json_script:'members-data' }};
{{ messages|json_script:'messages-data' }};
{{ utils.channels|json_script:'channel-list-data' }};
<script src="{% static "js/jquery-3.3.1.min.js" %}"></script>
<script src="{% static "js/bundle.js" %}"></script>
{% endblock %}

murmur_web/core/templates/core/workspace/navbar.html
<a class="brand" href="{%url "user:dash"%}">Murmur</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="{% url "ws:home" workspace %}">{{ workspace }}</a>
    </li>
  </ul>
  <div>
    <div class="nav-item d-inline"><a href="{% url "logout" %}">Logout</a></div>
    <div class="nav-item d-inline"><a href="{% url "ws:settings" workspace %}">Settings</a></div>
  </div>
</div>

murmur_web/core/templates/core/workspace/ws_create.html
{% extends 'core/base.html' %}

{% block title %}Create Workspace {% endblock %}
{% block navbar %}
{% include "core/user/navbar.html" %}
{% endblock %}

{% block content %}
    <div class="cover-container d-flex w-100 h-100 p-3 pt-5 mx-auto flex-column">
        <main role="main" class="inner cover">
            <div class="container signup-register-forms">
                <div class="container">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <p>
                                {{ field.label_tag }}<br>
                                {{ field }}
                                {% if field.help_text %}
                                    <small style="color: grey">{{ field.help_text }}</small>
                                {% endif %}
                                {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                                {% endfor %}
                            </p>
                        {% endfor %}
                        <button type="submit">Create</button>
                    </form>
                </div>
            </div>
        </main>
    </div>
{% endblock %}

murmur_web/core/templates/core/workspace/ws_home.html
{% extends 'core/base.html' %}

{% block content %}
    <p>Hi {{ user.username }}!</p>
    <p>You are in {{ ws_name }}</p>
    <div class="container text-center">
        <div class="row">
            <div class="col-sm-7">
                <div class="well">
                    <div id="channels">
                        {% for ch in ch_list %}
                            <li>
                                <p>
                                    <a href="/w/{{ ch }}/">
                                        <button class="btn btn-primary font-italic">
                                            {{ ch }}
                                        </button>
                                    </a>
                                </p>
                            </li>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <footer class="container-fluid text-left">
        <p><a href="{% url 'logout' %}">
            <button class="btn btn-secondary font-weight-bold font-italic">
                Logout
            </button>
        </a>
        <p><a href="{% url 'password_reset' %}">
            <button class="btn btn-secondary font-weight-bold font-italic">
                Reset Password
            </button>
        </a>
        </p>
    </footer>

{% endblock %}

murmur_web/core/templates/core/workspace/ws_newch.html
{% extends 'core/base.html' %}

{% block title %}Create Workspace {% endblock %}

{% block content %}
    <div class="cover-container d-flex w-100 h-100 p-3 pt-5 mx-auto flex-column">
        <main role="main" class="inner cover">
            <div class="container signup-register-forms">
                <div class="container">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <p>
                                {{ field.label_tag }}<br>
                                {{ field }}
                                {% if field.help_text %}
                                    <small style="color: grey">{{ field.help_text }}</small>
                                {% endif %}
                                {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                                {% endfor %}
                            </p>
                        {% endfor %}
                        <button type="submit">Create Channel</button>
                    </form>
                </div>
            </div>
        </main>
    </div>
{% endblock %}

murmur_web/core/templates/core/workspace/ws_setting.html
{% extends 'core/base.html' %}

{% block title %}Workspace Dashboard{% endblock %}

{% block content %}
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Dashboard</a></li>
                <li><a href="#">{{ws_name}}</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#"><span class="glyphicon glyphicon-user"></span> Settings</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container text-center">
    <div class="row">
        <div class="col-sm-3 well">
            <div class="well">
                {% for channel, members in data.items %}
                <h5><p>{{channel}}</p></h5>
                {% for member in members %}

                <ul>
                    <li>
                        <tr>{{ member }}</tr>
                    </li>
                </ul>
                {% endfor %}
                {% endfor %}

            </div>
        </div>
    </div>
</div>
{% endblock %}